server:
  port: 8080
  servlet:
    context-path: /bdp
spring:
  banner:
    location: classpath:/banner.txt

plugins:
  itsm:
    s3:
      host: 129.204.99.160
      port: 9000
      username: access_key
      password: secret_key